version: "3.9"
services:
  api:
    image: "registry.byniwee.cloud/php:${PHP_VERSION}"
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - "./api:/var/www/html"
      - "./api:/var/opt/app"
      - $HOME/.ssh:/home/niwee/.ssh
    working_dir: /var/www/html
    tty: true

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 2s
      timeout: 3s
      retries: 50
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./api:/var/www/html
      - ./log:/var/log/nginx


  node:
    image: "node:18"
    restart: unless-stopped
    command: ["/bin/bash", "-c", "yarn install && yarn run dev"]
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - "./:/app"
    working_dir: /app
    tty: true

  maildev:
    image: djfarrelly/maildev
    restart: unless-stopped
    env_file: .env
    environment:
      - ${MAILDEV_PORT:-1080}
    expose:
      - 80
