version: "3.9"
services:
  api:
    image: "registry.byniwee.cloud/php:${PHP_VERSION}"
    restart: unless-stopped
    env_file: .env
    user: niwee
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - "./api:/var/www/html"
      - "./api:/var/opt/app"
      - $HOME/.ssh:/home/niwee/.ssh
    working_dir: /var/www/html
    tty: true

  certbot:
    build: ./docker/certbot
    depends_on:
      - nextjs
    volumes:
      - ./config/ssl:/root/ssl

  nextjs:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    ports:
      - 3000:3000
    
  nginx:
    image: nginx:latest
    depends_on:
      certbot:
        condition: service_completed_successfully
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    restart: "unless-stopped"
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 2s
      timeout: 3s
      retries: 50
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - ./api:/var/www/html
      - ./log:/var/log/nginx
      - ./config/ssl:/etc/nginx/ssl

  maildev:
    image: djfarrelly/maildev
    restart: unless-stopped
    env_file: .env
    environment:
      - ${MAILDEV_PORT:-1080}
    expose:
      - 80
