version: "3.9"
services:
  app:
    image: "registry.byniwee.cloud/php:${PHP_VERSION}"
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - "$APP_DIR:$ROOT_DIR"
      - "$APP_DIR:/var/opt/app"
      - $HOME/.ssh:/home/niwee/.ssh
    working_dir: $ROOT_DIR
    tty: true

  caddy:
    image: "registry.byniwee.cloud/caddy:latest"
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: ["CMD", "caddy", "version"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      app:
        condition: service_started
    links:
      - "app"
    volumes_from:
      - "app"
    volumes:
      - "./config/caddy/Caddyfile:/etc/caddy/Caddyfile"
    ports:
      - 80:80
      - 443:443
    tty: true

  node:
    image: "node:18"
    restart: unless-stopped
    command: ["/bin/bash", "-c", "yarn install && yarn run dev"]
    env_file: .env
    healthcheck:
      test: ["CMD", "node", "-v"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      app:
        condition: service_started
    links:
      - "app"
    volumes:
      - "$APP_DIR/frontend:/app"
    working_dir: /app
    tty: true

  maildev:
    image: djfarrelly/maildev
    restart: unless-stopped
    env_file: .env
    environment:
      - ${MAILDEV_PORT:-1080}
    expose:
      - 80
