node_builder:
    image: node:16
    restart: "no"
    user: node
    volumes:
      - $APP_DIR:/app
    working_dir: /app
    command: bash -c "yarn"

  node:
    image: node:16
    restart: unless-stopped
    links:
      - "caddy"
    tty: true
    command: ["yarn", "dev"]
    user: node
    depends_on:
      caddy:
        condition: service_healthy
    volumes:
      - $APP_DIR:/app
    working_dir: /app
    ports:
      - "3000:3000"